### ISSUE TITLE
summarize_grading_vc step not working with latest docker image

### ISSUE THREAD

**Issue by nik9jovanovic** [bcbio/bcbio_validation_workflows#2]
Command is:
bcbio_nextgen.py runfn summarize_grading_vc cwl sentinel_runtime=cores,1,ram,3072 sentinel_parallel=multi-combined sentinel_outputs=validate_grading_summary,validate_grading_plots sentinel_inputs=vc_rec:record

Traceback (most recent call last):
File "/usr/local/bin/bcbio_nextgen.py", line 219, in <module>
runfn.process(kwargs["args"])
File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/runfn.py", line 33, in process
raise AttributeError("Did not find exposed function in bcbio.distributed.multitasks named '%s'" % args.name)
AttributeError: Did not find exposed function in bcbio.distributed.multitasks named 'summarize_grading_vc'

There is only summarize_vc in the new docker image instead of summarize_grading_vc function.

**Comment by chapmanb** [comment]
Sorry about this, we're working on releasing a new version of the workflow that supports all the bcbio backend changes. I'll hopefully have this released tomorrow and will update here when it's available. Thanks much for reporting the problem.

**Comment by chapmanb** [comment]
Thanks again for testing this. I pushed an updated version of the workflow here and linked on the Synapse GA4GH DREAM challenge site (https://www.synapse.org/#!Synapse:syn8507133/wiki/415976) that should resolve these issues. It should provide a lot of cleanup and improvements over the previous version, including support for "null"/null representation, extra inputs and secondaryFile representation. Please let us know if you run into any problems.

**Comment by nik9jovanovic** [comment]
Thank you for fixing this in such short notice!
