### ISSUE TITLE
Cannot download syn10466755

### ISSUE THREAD

**Issue by sangtaekim** [bcbio/bcbio_validation_workflows#3]
Hi ,

I am a certified synapse user, but still cannot download data files at syn10466755. The synapse client keeps saying "You do not have DOWNLOAD permissions for this file. The file has NOT been downloaded". I have no issue with other synapse IDs (e.g. syn9725771). Can you check?

Thanks,

Sangtae

**Comment by chapmanb** [comment]
Sangtae;
Thanks for trying this out and apologies for the issue. Could you re-try now when logged into synapse? Previously the files were only available to registered challenge participants but we've opened it up so any registered Synapse user can download. Please let us know if this doesn't fix it for you.
