### ISSUE TITLE
Could you provide correct path to reference materials?

### ISSUE THREAD

**Issue by mariafiruleva** [bcbio/bcbio_validation_workflows#9]
Hi,

I want to download file from RAS-panel using the [link](https://basespace.illumina.com/projects/36152117) from your repo, however, there is 403 error.

**Comment by chapmanb** [comment]
Thanks for the question. That link appears to still be valid, but you do have to sign up for Illumina Basespace to access it. The data is hosted there from the original Pisces team. Hope this helps.

**Comment by mariafiruleva** [comment]
Hi chapmanb,
I've signed up for Illumina Basespace, and I've got:

> You do not have access to the requested page .
> This may be the result of transfer or unsharing.
> 
> Try going back to the dashboard
> Or, go back to illumina.com
> Or, try My Account

**Comment by chapmanb** [comment]
Sorry about the continued issues. I'm not sure why you're having access issues with this. The data was provided by the Pisces team at Illumina and I'd suggest raising an issue:

https://github.com/Illumina/Pisces

and hopefully they'll be able to help with managing access. Hope this helps.
